// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8MLoSezadMDA25d1pRWbMFxN-SnegR2s',
    appId: '1:274700936727:web:dedb3ce01694413972de52',
    messagingSenderId: '274700936727',
    projectId: 'todo-app-644bc',
    authDomain: 'todo-app-644bc.firebaseapp.com',
    storageBucket: 'todo-app-644bc.appspot.com',
    measurementId: 'G-HSF57B67RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXBH9Tuas_9vmnb9mtlwrtwquSWw3LLYU',
    appId: '1:274700936727:android:1f56744c949ff59d72de52',
    messagingSenderId: '274700936727',
    projectId: 'todo-app-644bc',
    storageBucket: 'todo-app-644bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtse18fxLUm4lFawuWyKg9lSNhl2vTrZg',
    appId: '1:274700936727:ios:7625a612470e810472de52',
    messagingSenderId: '274700936727',
    projectId: 'todo-app-644bc',
    storageBucket: 'todo-app-644bc.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtse18fxLUm4lFawuWyKg9lSNhl2vTrZg',
    appId: '1:274700936727:ios:f5e6dae9f9ef8bc672de52',
    messagingSenderId: '274700936727',
    projectId: 'todo-app-644bc',
    storageBucket: 'todo-app-644bc.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
